# Sample .circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Running build steps"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Running test steps"
      - run:
        name: "GitHub Parameters"
        command: |
          echo pipeline.trigger_parameters.github_app.commit_message: << pipeline.trigger_parameters.github_app.commit_message >>
          echo pipeline.trigger_parameters.github_app.commit_title: << pipeline.trigger_parameters.github_app.commit_title >>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: /main/
